### ISSUE TITLE
Fix update name

### ISSUE THREAD

**Issue by originalnicodr** [originalnicodr/CuratorDiscordBot#5]
Seems that the last bot update broke the update game command.

This is the traceback:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
await coro(*args, **kwargs)
File "/bot/bot.py", line 843, in on_message
await bot.process_commands(message)
File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1392, in process_commands
await self.invoke(ctx) # type: ignore
File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
await ctx.command.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1021, in invoke
await self.prepare(ctx)
File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 925, in prepare
if not await self.can_run(ctx):
File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1288, in can_run
return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
File "/usr/local/lib/python3.10/site-packages/discord/utils.py", line 705, in async_all
elem = await elem
File "/bot/bot.py", line 122, in is_user_allowed
member = get_framed_server().get_member(ctx.author.id)
NameError: name 'get_framed_server' is not defined
```

Shouldn't be difficult to test, but I am very busy atm, so will try to look into it next weekend so I can properly test the fix as well.

**Comment by originalnicodr** [comment]
Fixed on 0a5c387
